### ISSUE TITLE
CT Lint failed with status code 3:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phet-lib#4]
```
phet-lib : lint
Lint failed with status code 3:
Loading "Gruntfile.js" tasks...ERROR
>> Error [ERR_REQUIRE_ESM]: require() of ES Module /data/share/phet/continuous-testing/ct-main/ct-snapshots/1707840302549/phet-lib/Gruntfile.js from /data/share/phet/continuous-testing/ct-main/ct-snapshots/1707840302549/phet-lib/node_modules/grunt/lib/grunt/task.js not supported.
>> Gruntfile.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
>> Instead rename Gruntfile.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /data/share/phet/continuous-testing/ct-main/ct-snapshots/1707840302549/phet-lib/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
Warning: Task "lint" not found. Use --force to continue.

Aborted due to warnings.
Snapshot from 2/13/2024, 9:05:02 AM

----------------------------------

phet-lib : pageload : /doc/layout-exemplars.html
http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/phet-lib/doc/layout-exemplars.html
TypeError: $ is not a function
@http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/sherpa/lib/bootstrap-2.2.2.js:29:4
at <unknown> (http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/sherpa/lib/bootstrap-2.2.2.js:29:4)
at <unknown> (http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/sherpa/lib/bootstrap-2.2.2.js:60:2)
[URL] http://127.0.0.1/continuous-testing/aqua/html/pageload-test.html?url=..%2F..%2Fct-snapshots%2F1707840302549%2Fphet-lib%2Fdoc%2Flayout-exemplars.html&testInfo=%7B%22test%22%3A%5B%22phet-lib%22%2C%22pageload%22%2C%22%2Fdoc%2Flayout-exemplars.html%22%5D%2C%22snapshotName%22%3A%22snapshot-1707840302549%22%2C%22timestamp%22%3A1707840749181%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/pageload-test.html?url=..%2F..%2Fct-snapshots%2F1707840302549%2Fphet-lib%2Fdoc%2Flayout-exemplars.html&testInfo=%7B%22test%22%3A%5B%22phet-lib%22%2C%22pageload%22%2C%22%2Fdoc%2Flayout-exemplars.html%22%5D%2C%22snapshotName%22%3A%22snapshot-1707840302549%22%2C%22timestamp%22%3A1707840749181%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/phet-lib/doc/layout-exemplars.html
[CONSOLE] [JavaScript Warning: "Loading failed for the <script> with source “http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/phet-lib/dist/phet-lib.min.js”." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/phet-lib/doc/layout-exemplars.html" line: 11}]
[CONSOLE] [JavaScript Warning: "This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1707840302549/phet-lib/doc/layout-exemplars.html" line: 0}]
[CONSOLE] error
[PAGE ERROR] TypeError: $ is not a function
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined
[PAGE ERROR] ReferenceError: phet is not defined

id: "Sparky Node Firefox"
Snapshot from 2/13/2024, 9:05:02 AM
```

**Comment by zepumph** [comment]
Taking a look now.

**Comment by zepumph** [comment]
The layout html is now passing, and `grunt lint` isn't failling, but it also isn't working. I'm unsure how to support lint in phet-lib. I'll make another issue.
